# Generated by Django 3.1.7 on 2021-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_cmd_question_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_apply',
            name='office',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
