# Generated by Django 3.1.7 on 2021-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_business_apply_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_apply',
            name='assign_num',
            field=models.IntegerField(max_length=4),
        ),
    ]
