# Generated by Django 3.1.7 on 2021-06-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20210608_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmd_question',
            name='bussiness_num',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='bussiness_num',
            field=models.CharField(max_length=4),
        ),
    ]
